spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BankingDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: D0UGL@$mysql

  jpa:
    show-sql: true

  application:
    name: university-student-portal

server:
  port: 8080
